name: Monitor Google Sheets

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Run the script
      run: |
        python Trigger.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

    - name: Upload Report
      uses: actions/upload-artifact@v2
      with:
        name: Absence_Report
        path: Final_User_Data.csv
