name: Monitor Google Sheets

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every 24 hours at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run_script:
    runs-on: ubuntu-latest  
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to latest version

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to latest version
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  
    
    - name: Run the script
      run: python Trigger.py  
      env: 
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3  # Updated from v2 to v3
      with:
        name: Final_User_Data
        path: Final_User_Data.csv
