name: Monitor Google Sheets

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every 24 hours at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run_script:
    runs-on: ubuntu-latest  # or choose the OS that fits your needs (e.g., windows-latest, macos-latest)
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # specify your required Python version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel  # Upgrade essential tools
        pip install -r requirements.txt

    - name: Run the script
      run: |
        python Trigger.py  # Replace with the name of your script
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
