name: Monitor Google Sheets

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every 24 hours at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run_script:
    runs-on: ubuntu-latest  # Run on latest Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to the latest version

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated version
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      run: python Trigger.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        SHEET1_NAME: ${{ secrets.SHEET1_NAME }}
        SHEET1_WORKSHEET: ${{ secrets.SHEET1_WORKSHEET }}
        SHEET2_NAME: ${{ secrets.SHEET2_NAME }}
        SHEET2_WORKSHEET: ${{ secrets.SHEET2_WORKSHEET }}
        NO_OF_DAYS: ${{ secrets.NO_OF_DAYS }}
