name: Monitor Google Sheet

on:
  schedule:
    # Run every 24 hours at midnight UTC
    - cron: '0 0 * * *'
    
jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread pandas google-auth

      - name: Run script
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
          SHEET1_NAME: ${{ secrets.SHEET1_NAME }}
          SHEET2_NAME: ${{ secrets.SHEET2_NAME }}
          NO_OF_DAYS: ${{ secrets.NO_OF_DAYS }}
        run: |
          python script_name.py  # Replace with your actual script file name
